# Generated by Django 4.0.6 on 2022-12-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrado', models.BooleanField(default=False)),
                ('creado_fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('creado_usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('modificado_fecha', models.DateTimeField(auto_now=True, null=True)),
                ('modificado_usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('borrado_fecha', models.DateTimeField(blank=True, null=True)),
                ('borrado_usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('dni', models.CharField(max_length=50, unique=True, verbose_name='DNI')),
                ('apellido', models.CharField(max_length=150, verbose_name='APELLIDO')),
                ('nombre', models.CharField(max_length=150, verbose_name='NOMBRE')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='CORREO_ELECTRONICO')),
                ('telefono', models.CharField(max_length=50, verbose_name='TELEFONO')),
                ('matricula', models.CharField(max_length=50, verbose_name='MATRICULA_PROFESIONAL')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
